#!/bin/sh

# Sudoers
#--------

/usr/sbin/addsudo /usr/sbin/slapadd app-openldap-core
/usr/sbin/addsudo /usr/sbin/slapcat app-openldap-core

# Set default sysconfig
#----------------------

# ClearOS 6 only
if [ -e /etc/sysconfig/ldap ]; then
    CHECK=`grep ^BIND_POLICY /etc/sysconfig/ldap 2>/dev/null`

    if [ -z "$CHECK" ]; then
        logger -p local6.notice -t installer "app-openldap-core - updating LDAP sysconfig"
        cp /usr/clearos/apps/openldap/deploy/ldap.sysconfig /etc/sysconfig/ldap
    fi
fi

# Add OwnCloud schema
#--------------------

# config.php check: don't bother with upgrade if LDAP not yet provisioned
if [ -e /var/clearos/openldap/config.php ]; then
    CHECK=`grep ^include[[:space:]]*/etc/openldap/schema/owncloud.schema /etc/openldap/slapd.conf 2>/dev/null`

    if [ -z "$CHECK" ]; then
        logger -p local6.notice -t installer "app-openldap-core - adding owncloud schema"
        # Messy - using samba3 as a file marker
        sed -i -e "s/^include[[:space:]]*\/etc\/openldap\/schema\/samba3.schema/include \/etc\/openldap\/schema\/samba3.schema\n\n# OwnCloud\ninclude \/etc\/openldap\/schema\/owncloud.schema/" /etc/openldap/slapd.conf 
    fi
fi

# Configure server certificates
#------------------------------

/var/clearos/events/certificate_manager/openldap

# Restart LDAP in case of schema changes
#---------------------------------------

/sbin/service slapd condrestart >/dev/null 2>&1
